var elems = [
	{
		id : 1,
		playerOneName: "Al Shabab",
		playerOneImg : "",
		playerTwoName: "Al fateh",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500

	},
	{
		id : 2,
		playerOneName: "Al Hilal",
		playerOneImg : "",
		playerTwoName: "Al Ahli",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500
	},
	{
		id : 3,
		playerOneName: "Al Shabab",
		playerOneImg : "",
		playerTwoName: "Al Hilal",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500
	},
	{
		id : 4,
		playerOneName: "Al Shabab",
		playerOneImg : "",
		playerTwoName: "Al Ahli",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500
	},
	{
		id : 5,
		playerOneName: "Al Hilal",
		playerOneImg : "",
		playerTwoName: "Al fateh",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500
	},
	{
		id : 6,
		playerOneName: "Al Ahli",
		playerOneImg : "",
		playerTwoName: "Al fateh",
		playerTwoImg : "",
		vs : "",
		title: "",	
		titleLogo: "",
		coming : "",
		date: "Sat 12 Nov 2016",
		time: "10:00 PM",
		place: "Riyadh, king Fahad International Stadium",
		event: "football",
		seatsRemaining: 20, 
		seatsTotal: 500
	}


]

export default elems;